export enum FileType {
  TEXT_PLAIN = 'text/plain',
  APPLICATION_PDF = 'application/pdf',
  IMAGE_JPEG = 'image/jpeg',
  IMAGE_PNG = 'image/png',
  IMAGE_GIF = 'image/gif',
  IMAGE_BMP = 'image/bmp',
  AUDIO_MPEG = 'audio/mpeg',
  AUDIO_WAV = 'audio/wav',
  VIDEO_MP4 = 'video/mp4',
  VIDEO_MPEG = 'video/mpeg',
  APPLICATION_JSON = 'application/json',
  APPLICATION_XML = 'application/xml',
  APPLICATION_MSWORD = 'application/msword',
  APPLICATION_MSEXCEL = 'application/vnd.ms-excel',
  APPLICATION_MSPOWERPOINT = 'application/vnd.ms-powerpoint',
  APPLICATION_ZIP = 'application/zip',
  APPLICATION_GZIP = 'application/gzip',
  APPLICATION_TAR = 'application/x-tar',
  APPLICATION_RTF = 'application/rtf',
  APPLICATION_OCTET_STREAM = 'application/octet-stream',
}
